# Generated by Django 4.0.6 on 2023-01-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('manager', 'Manager'), ('developer', 'Developer'), ('team-leader', 'Team-Leader')], max_length=15)),
                ('salary', models.FloatField(default=0.0, null=True)),
                ('join_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
